name: ðŸš€ CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ vars.IMAGE_NAME }}

    steps:
      - name: â¬‡ï¸ Checkout Code
        uses: actions/checkout@v4

      - name: ðŸ§ª Load CI Environment Variables
        run: |
          while IFS='=' read -r key value
          do
            echo "$key=$value" >> $GITHUB_ENV
          done < .ci.env
      
      - name: Debug ENV values
        run: |
          echo "IMAGE_NAME=$IMAGE_NAME"
          echo "PYTHON_VERSION=$PYTHON_VERSION"
          echo "IMAGE_VERSION=$IMAGE_VERSION"
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Image
        run: |
          docker buildx build --load \
            --build-arg IMAGE_TAG=$IMAGE_VERSION \
            --build-arg PYTHON_VERSION=$PYTHON_VERSION \
            -t $IMAGE_NAME:$IMAGE_VERSION \
            .
          docker push $IMAGE_NAME:$IMAGE_VERSION

      - name: Build Summary
        run: |
          echo "### Docker Image Built Successfully!" >> $GITHUB_STEP_SUMMARY
          echo "**Image:** \`$IMAGE_NAME:$IMAGE_VERSION\`" >> $GITHUB_STEP_SUMMARY

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ vars.IMAGE_NAME }}
      STACK_FILE: ${{ vars.STACK_FILE }}
      STACK_NAME: ${{ vars.STACK_NAME }}
      DEPLOY_PATH: ${{ vars.DEPLOY_PATH }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: ðŸ§ª Load CI Environment Variables
        run: |
          while IFS='=' read -r key value
          do
            echo "$key=$value" >> $GITHUB_ENV
          done < .ci.env

      - name: ðŸ” Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: ðŸš€ Deploy to Server
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          IMAGE_VERSION: ${{ env.IMAGE_VERSION }}
        run: |
          ssh -o StrictHostKeyChecking=no -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" << EOF
            set -e

            cd "$DEPLOY_PATH"

            echo "ðŸ“ Updating .env with image version..."
            sed -i 's/^IMAGE_VERSION=.*/IMAGE_VERSION='"$IMAGE_VERSION"'/' .env

            echo "ðŸš¢ Deploying stack..."
            docker stack deploy -c <(docker-compose -f "$STACK_FILE" config) "$STACK_NAME"

            echo "â³ Waiting for stack to stabilize..."
            sleep 30

            echo "ðŸ” Service status:"
            docker stack services "$STACK_NAME"
          EOF

      - name: âœ… Deployment Summary
        run: |
          echo "### ðŸŽ‰ Deployment Successful!" >> $GITHUB_STEP_SUMMARY
          echo "**Server:** \`${{ secrets.SSH_HOST }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Stack:** \`$STACK_NAME\`" >> $GITHUB_STEP_SUMMARY
          echo "**Image:** \`$IMAGE_NAME:$IMAGE_VERSION\`" >> $GITHUB_STEP_SUMMARY
