name: ðŸš€ Build and Deploy to Azure App Service

on:
  push:
    branches: [ main, master, dev ]
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      image_version:
        description: 'Image version/tag to build'
        required: true
        default: 'latest'

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/api-name
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.image_tag.outputs.tag }}
    
    steps:
      - name: â¬‡ï¸ Checkout Code
        uses: actions/checkout@v4

      - name: ðŸ§ª Load CI Environment Variables
        run: |
          if [ -f .ci.env ]; then
            while IFS='=' read -r key value
            do
              [[ $key =~ ^#.*$ ]] && continue
              [[ -z $key ]] && continue
              value=$(echo "$value" | sed 's/#.*//' | xargs)
              echo "$key=$value" >> $GITHUB_ENV
            done < .ci.env
          fi
      
      - name: ðŸ·ï¸ Determine Image Tag
        id: image_tag
        run: |
          if [ -n "${{ github.event.inputs.image_version }}" ]; then
            echo "tag=${{ github.event.inputs.image_version }}" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          elif [ -n "$IMAGE_VERSION" ]; then
            echo "tag=$IMAGE_VERSION" >> $GITHUB_OUTPUT
          else
            echo "tag=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
          fi
          
      - name: ðŸ³ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ðŸ” Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: ðŸš€ Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH || 'Dockerfile' }}
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.image_tag.outputs.tag }}
            ${{ env.IMAGE_NAME }}:latest
          build-args: |
            PYTHON_VERSION=${{ env.PYTHON_VERSION || '3.13' }}-slim
            IMAGE_TAG=${{ steps.image_tag.outputs.tag }}

  deploy-to-azure:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
      - name: â¬‡ï¸ Checkout Code
        uses: actions/checkout@v4

      - name: ðŸ§ª Load CI Environment Variables
        run: |
          if [ -f .ci.env ]; then
            while IFS='=' read -r key value
            do
              [[ $key =~ ^#.*$ ]] && continue
              [[ -z $key ]] && continue
              value=$(echo "$value" | sed 's/#.*//' | xargs)
              echo "$key=$value" >> $GITHUB_ENV
            done < .ci.env
          fi

      - name: ðŸ” Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ðŸš€ Deploy to Azure App Service
        env:
          IMAGE_TAG: ${{ needs.build-and-push.outputs.image_tag }}
        run: |
          echo "Deploying to Azure App Service..."
          
          # Configure App Service to use Docker container
          az webapp config container set \
            --name ${{ env.AZURE_APP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --docker-custom-image-name ${{ env.IMAGE_NAME }}:${IMAGE_TAG} \
            --docker-registry-server-url https://index.docker.io \
            --docker-registry-server-user ${{ secrets.DOCKER_USERNAME }} \
            --docker-registry-server-password ${{ secrets.DOCKER_PASSWORD }}
          
          # Configure environment variables
          az webapp config appsettings set \
            --name ${{ env.AZURE_APP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --settings \
              PORT=8000 \
              DEBUG=false \
              DATABASE_URL="${{ secrets.PROD_DATABASE_URL }}" \
              REDIS_URL="${{ secrets.PROD_REDIS_URL }}" \
              ADMIN_API_KEY="${{ secrets.PROD_ADMIN_API_KEY }}" \
              WEBSITES_PORT=8000
          
          # Restart the app
          az webapp restart \
            --name ${{ env.AZURE_APP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }}
          
          # Get URL
          URL=$(az webapp show \
            --name ${{ env.AZURE_APP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --query defaultHostName \
            --output tsv)
          
          echo "App deployed at: https://${URL}"
          echo "URL=${URL}" >> $GITHUB_ENV

      - name: âœ… Deployment Summary
        run: |
          echo "### ðŸŽ‰ Deployment Successful!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Azure App Service:** \`${{ env.AZURE_APP_NAME }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Resource Group:** \`${{ env.AZURE_RESOURCE_GROUP }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Image:** \`${{ env.IMAGE_NAME }}:${{ needs.build-and-push.outputs.image_tag }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**URL:** https://${{ env.URL }}" >> $GITHUB_STEP_SUMMARY
